/* FILE: packages/shared/constants/icons.ts */

export const GESTURE_CATEGORY_ICONS = {
  BUILT_IN_HAND: { iconName: "waving_hand", iconType: "material-icons", defaultEmoji: "👋" },
  CUSTOM_HAND: { iconName: "front_hand", iconType: "material-icons", defaultEmoji: "🫱" },
  CUSTOM_POSE: { iconName: "emoji_people", iconType: "material-icons", defaultEmoji: "🙋🏻‍♂️" },
  UNKNOWN: { iconName: "help_outline", iconType: "material-icons", defaultEmoji: "❔" },
  UI_WEBCAM: { iconName: "photo_camera", iconType: "material-icons" },
  UI_RTSP_STREAM: { iconName: "router", iconType: "material-icons" },
  UI_FEATURES_DROPDOWN_TRIGGER: { iconName: "sensors", iconType: "material-icons" },
  UI_HANDS_LANDMARKS_DROPDOWN_TRIGGER: { iconName: "handshake", iconType: "material-icons" },
  UI_POSE_LANDMARK_TOGGLE: { iconName: "timeline", iconType: "material-icons" },
  UI_HAND_LANDMARK_HIDE: { iconName: "do_not_touch", iconType: "material-icons" },
  UI_HAND_DETECT_ONE: { iconName: "pan_tool", iconType: "material-icons" },
  UI_HAND_DETECT_TWO: { iconName: "sign_language", iconType: "material-icons" },
  UI_VIDEO_MIRROR: { iconName: "flip", iconType: "material-icons" },
  UI_VIDEO_FULLSCREEN: { iconName: "fullscreen", iconType: "material-icons" },
  UI_VIDEO_FULLSCREEN_EXIT: { iconName: "fullscreen_exit", iconType: "material-icons" },
  UI_FLIP_CAMERA: { iconName: "cameraswitch", iconType: "material-icons" },
  UI_DISPLAY_ADJUSTMENTS: { iconName: "brightness_6", iconType: "material-icons" },
  UI_AI_TUNING: { iconName: "graphic_eq", iconType: "material-icons" },
  UI_STOP_STREAM: { iconName: "stop", iconType: "material-icons" },
  UI_VISIBILITY_ON: { iconName: "visibility", iconType: "material-icons" },
  UI_VISIBILITY_OFF: { iconName: "visibility_off", iconType: "material-icons" },
  UI_TIMER: { iconName: "timer", iconType: "material-icons" },
  UI_CHEVRON_LEFT: { iconName: "chevron_left", iconType: "material-icons" },
  UI_CHEVRON_RIGHT: { iconName: "chevron_right", iconType: "material-icons" },
  UI_ADD: { iconName: "add_circle_outline", iconType: "material-icons" },
  UI_DELETE: { iconName: "delete", iconType: "material-icons" },
  UI_CLOSE: { iconName: "mdi-close", iconType: "mdi" },
  UI_SAVE: { iconName: "save", iconType: "material-icons" },
  UI_CANCEL: { iconName: "cancel", iconType: "material-icons" },
  UI_CONFIRM: { iconName: "check_circle", iconType: "material-icons" },
  UI_UPLOAD: { iconName: "upload", iconType: "material-icons" },
  UI_FILE_ATTACH: { iconName: "upload_file", iconType: "material-icons" },
  UI_ANALYZE: { iconName: "analytics", iconType: "material-icons" },
  UI_HOURGLASS: { iconName: "hourglass_top", iconType: "material-icons" },
  UI_SETTINGS: { iconName: "settings", iconType: "material-icons" },
  UI_TUNE: { iconName: "tune", iconType: "material-icons" },
  UI_PLAY: { iconName: "play_arrow", iconType: "material-icons" },
  UI_HISTORY: { iconName: "history", iconType: "material-icons" },
  UI_DOCS: { iconName: "menu_book", iconType: "material-icons" },
  UI_WS_CONNECTED: { iconName: "cloud_done", iconType: "material-icons" },
  UI_WS_DISCONNECTED: { iconName: "cloud_off", iconType: "material-icons" },
  UI_WS_CONNECTING: { iconName: "sync", iconType: "material-icons" },
  UI_RESOLUTION_NHD: { iconName: "aspect_ratio", iconType: "material-icons" },
  UI_RESOLUTION_SD: { iconName: "settings_overscan", iconType: "material-icons" },
  UI_RESOLUTION_HD: { iconName: "hd", iconType: "material-icons" },
  UI_CHECK_CIRCLE: { iconName: "check_circle_outline", iconType: "material-icons" },
  UI_HIGHLIGHT_OFF: { iconName: "highlight_off", iconType: "material-icons" },
  UI_NETWORK_CHECK: { iconName: "network_check", iconType: "material-icons" },
  UI_CAMERA_OUTLINE: { iconName: 'mdi-camera-outline', iconType: 'mdi' },
  UI_LIST_CHECK: { iconName: 'mdi-format-list-checks', iconType: 'mdi' },
  UI_LIGHT_MODE: { iconName: "light_mode", iconType: "material-icons" },
  UI_SYSTEM_MODE: { iconName: "brightness_auto", iconType: "material-icons" },
  UI_DARK_MODE: { iconName: "dark_mode", iconType: "material-icons" },
  UI_INFO: { iconName: "info_outline", iconType: "material-icons" },
  UI_RESET: { iconName: "restart_alt", iconType: "material-icons" },
  UI_LINK: { iconName: "link", iconType: "material-icons" },
  UI_CROP: { iconName: "crop", iconType: "material-icons" },
  UI_NOTES: { iconName: "notes", iconType: "material-icons" },
  UI_KEY: { iconName: "vpn_key", iconType: "material-icons" },
  UI_ACTION: { iconName: "send", iconType: "material-icons" },
  UI_ERROR: { iconName: "error_outline", iconType: "material-icons" },
  UI_TOGGLE_ON: { iconName: "toggle_on", iconType: "material-icons" },
  UI_TOGGLE_OFF: { iconName: "toggle_off", iconType: "material-icons" },
  // Newly Added Icons
  UI_EXTENSION: { iconName: "extension", iconType: "material-icons" },
  UI_VIDEOCAM: { iconName: "videocam", iconType: "material-icons" },
  UI_ARROW_DROP_DOWN: { iconName: "arrow_drop_down", iconType: "material-icons" },
  UI_GESTURE: { iconName: "gesture", iconType: "material-icons" },
  UI_EDIT_NOTE: { iconName: "edit_note", iconType: "material-icons" },
  UI_CAMERA: { iconName: "camera", iconType: "material-icons" },
  UI_BIOTECH: { iconName: "biotech", iconType: "material-icons" },
  UI_TERMINAL: { iconName: "terminal", iconType: "material-icons" },
  UI_DESKTOP: { iconName: "desktop_windows", iconType: "material-icons" },
  UI_DNS: { iconName: "dns", iconType: "material-icons" },
  UI_SLIDESHOW: { iconName: "slideshow", iconType: "material-icons" },
  UI_WEBHOOK: { iconName: "webhook", iconType: "material-icons" },
  UI_HTTP: { iconName: "http", iconType: "material-icons" },
} as const;

export type GestureCategoryIconType = keyof typeof GESTURE_CATEGORY_ICONS;