/* FILE: packages/frontend/src/core/dom-elements.ts */
// Aggregates and validates all DOM element queries for the application.

export interface AllDOMElements {
  [key: string]: HTMLElement | SVGElement | HTMLInputElement | HTMLButtonElement | HTMLSelectElement | HTMLTextAreaElement | HTMLFormElement | null | undefined;
}

export function getAllDOMElements(): AllDOMElements {
  const elements: AllDOMElements = {
    appTitle: document.getElementById("appTitle"),
    wsStatusIndicator: document.getElementById("wsStatusIndicator"),
    mobileControlsContainer: null, 
    headerToggleGroupsContainer: document.querySelector(".header-toggle-groups-container") as HTMLElement | null,
    languageSelectGroupHeader: document.getElementById("languageSelectGroupHeader"),
    mainSettingsToggle: document.getElementById("mainSettingsToggle"),
    cameraSelectButton: document.getElementById("cameraSelectButton"),
    
    gestureAlertDiv: document.getElementById("gestureAlert"),
    gestureAlertTextSpan: document.getElementById("gestureAlertText"),
    bottomNav: document.querySelector(".bottom-nav") as HTMLElement | null,
    gestureConfigToggleMobile: document.getElementById("gestureConfigToggleMobile"),
    historyToggleMobile: document.getElementById("historyToggleMobile"),
    bottomNavGesturesLabel: document.getElementById("bottomNavGesturesLabel"),
    bottomNavHistoryLabel: document.getElementById("bottomNavHistoryLabel"),
    sidebarBackdrop: document.getElementById("sidebarBackdrop"),
    desktopConfigListTitle: document.getElementById("desktopConfigListTitle"),
    liveFeedTitle: document.getElementById("liveFeedTitle"),
    gestureSettingsTitle: document.getElementById("gestureSettingsTitle"),
    configListContainer: document.getElementById("configListContainer"),
    configListDiv: document.getElementById("configList"),
    inactiveConfigListDiv: document.getElementById("inactiveConfigList"),
    customHandGestureListContainer: document.getElementById("customHandGestureListContainer"),
    customHandGestureListPlaceholder: document.getElementById("customHandGestureListPlaceholder"),
    customPoseGestureListContainer: document.getElementById("customPoseGestureListContainer"),
    customPoseGestureListPlaceholder: document.getElementById("customPoseGestureListPlaceholder"),
    toggleVideoButton: document.getElementById("toggleVideoButton"),
    toggleConfigListButton: document.getElementById("toggleConfigListButton"),
    videoContainer: document.querySelector(".video-container") as HTMLElement | null,
    
    // Sidebars & Toggles
    configSidebar: document.getElementById("configSidebar"),
    historySidebar: document.getElementById("historySidebar"),
    gestureHistoryDiv: document.getElementById("gestureHistory"),
    configSidebarToggleBtn: document.getElementById("configSidebarToggleBtn"),
    historySidebarToggleBtn: document.getElementById("historySidebarToggleBtn"),
    configSidebarHeaderCloseBtn: document.getElementById("configSidebarHeaderCloseBtn"),
    historySidebarHeaderCloseBtn: document.getElementById("historySidebarHeaderCloseBtn"),
    
    mainSettingsModal: document.getElementById("mainSettingsModal"),
    settingsModalTitle: document.getElementById("settingsModalTitle"),
    mainSettingsCloseButton: document.getElementById("mainSettingsCloseButton"),
    settingsTabs: document.getElementById("settingsTabs"),
    customGesturesTabButton: document.getElementById("customGesturesTabButton"),
    appVersionDisplaySettings: document.getElementById("appVersionDisplaySettings"),
    cameraSelectModal: document.getElementById("cameraSelectModal"),
    cameraList: document.getElementById("cameraList"),
    cameraModalHeader: document.getElementById("cameraModalHeader"),
    cameraListPlaceholder: document.getElementById("cameraListPlaceholder"),
    cameraSelectCloseButton: document.getElementById("cameraSelectCloseButton"),
    rtspSourceListContainer: document.getElementById("rtspSourceListContainer"),
    rtspListActionsContainer: document.getElementById("rtspListActionsContainer"),
    rtspListPlaceholder: document.getElementById("rtspListPlaceholder"),
    rtspAddNewButton: document.getElementById("rtspAddNewButton"),
    rtspAddEditFormContainer: document.getElementById("rtspAddEditFormContainer"),
    rtspFormTitle: document.getElementById("rtspFormTitle"),
    rtspEditIndex: document.getElementById("rtspEditIndex"),
    rtspSourceName: document.getElementById("rtspSourceName"),
    rtspSourceUrl: document.getElementById("rtspSourceUrl"),
    rtspNameLabel: document.getElementById("rtspNameLabel"),
    rtspUrlLabel: document.getElementById("rtspUrlLabel"),
    rtspUrlHelp: document.getElementById("rtspUrlHelp"),
    rtspSaveSourceButton: document.getElementById("rtspSaveSourceButton"),
    rtspCancelEditButton: document.getElementById("rtspCancelEditButton"),
    cancelEditButtonLabel: document.getElementById("cancelEditButtonLabel"),
    rtspSourceOnDemand: document.getElementById("rtspSourceOnDemand"),
    rtspSourceOnDemandLabel: document.getElementById("rtspSourceOnDemandLabel"),
    rtspRoiSettingsLabel: document.getElementById("rtspRoiSettingsLabel"),
    rtspRoiX: document.getElementById("rtspRoiX"),
    rtspRoiY: document.getElementById("rtspRoiY"),
    rtspRoiWidth: document.getElementById("rtspRoiWidth"),
    rtspRoiHeight: document.getElementById("rtspRoiHeight"),
    rtspRoiXLabel: document.getElementById("rtspRoiXLabel"),
    rtspRoiYLabel: document.getElementById("rtspRoiYLabel"),
    rtspRoiWidthLabel: document.getElementById("rtspRoiWidthLabel"),
    rtspRoiHeightLabel: document.getElementById("rtspRoiHeightLabel"),
    rtspRoiHelp: document.getElementById("rtspRoiHelp"),
    colorModeToggleGroup: document.getElementById("colorModeToggleGroup"),
    themeToggleGroup: document.getElementById("themeToggleGroup"),
    themeList: document.getElementById("themeList"),
    themeSelectionLabel: document.getElementById("themeSelectionLabel"),
    colorModeSelectionLabel: document.getElementById("colorModeSelectionLabel"),
    globalCooldownSlider: document.getElementById("globalCooldownSlider"),
    globalCooldownValue: document.getElementById("globalCooldownValue"),
    resolutionSelectGroup: document.getElementById("resolutionSelectGroup"),
    targetFpsSelectGroup: document.getElementById("targetFpsSelectGroup"),
    telemetryToggleGroup: document.getElementById("telemetryToggleGroup"),
    telemetryEnableButton: document.getElementById("telemetryEnableButton"),
    telemetryDisableButton: document.getElementById("telemetryDisableButton"),
    languageLabel: document.getElementById("languageLabel"),
    globalCooldownLabel: document.getElementById("globalCooldownLabel"),
    resolutionPrefLabel: document.getElementById("resolutionPrefLabel"),
    resolutionHelp: document.getElementById("resolutionHelp"),
    targetFpsLabel: document.getElementById("targetFpsLabel"),
    telemetryEnabledLabel: document.getElementById("telemetryEnabledLabel"),
    telemetryEnableLabelText: document.getElementById("telemetryEnableLabelText"),
    telemetryDisableLabelText: document.getElementById("telemetryDisableLabelText"),
    targetFpsHelp: document.getElementById("targetFpsHelp"),
    telemetryEnabledHelp: document.getElementById("telemetryEnabledHelp"),
    featureToggleGroup: document.getElementById("featureToggleGroup"),
    landmarkVisibilityGroup: document.getElementById("landmarkVisibilityGroup"),
    numHandsToggleGroup: document.getElementById("numHandsToggleGroup"),
    enableFeaturesLabel: document.getElementById("enableFeaturesLabel"),
    showLandmarksLabel: document.getElementById("showLandmarksLabel"),
    detectionFeaturesHelp: document.getElementById("detectionFeaturesHelp"),
    showLandmarksHelp: document.getElementById("showLandmarksHelp"),
    builtInHandButtonText: document.getElementById("builtInHandButtonText"),
    customGesturesButtonText: document.getElementById("customGesturesButtonText"),
    poseDetectionButtonText: document.getElementById("poseDetectionButtonText"),
    handLandmarksLabelText: document.getElementById("handLandmarksLabelText"),
    poseLandmarksLabelText: document.getElementById("poseLandmarksLabelText"),
    numHandsLegend: document.getElementById("numHandsLegend"),
    numHandsOneButtonText: document.getElementById("numHandsOneButtonText"),
    numHandsTwoButtonText: document.getElementById("numHandsTwoButtonText"),
    customGestureUploadForm: document.getElementById("customGestureUploadForm"),
    customGestureFile: document.getElementById("customGestureFile"),
    customGestureDesc: document.getElementById("customGestureDesc"),
    uploadCustomGestureBtn: document.getElementById("uploadCustomGestureBtn"),
    cancelCustomGestureImportBtn: document.getElementById("cancelCustomGestureImportBtn"),
    customGestureSecurityWarningIcon: document.getElementById("customGestureSecurityWarningIcon"),
    customGestureDescGroup: document.getElementById("customGestureDescGroup"),
    docsModal: document.getElementById("docsModal"),
    docsCloseButton: document.getElementById("docsCloseButton"),
    docsModalTitle: document.getElementById("docsModalTitle"),
    modalTocSidebar: document.getElementById("modalTocSidebar"),
    modalDocsContent: document.getElementById("modalDocsContent"),
    modalContent: document.getElementById("modalContent"),
    modalTocList: document.getElementById("modalTocList"),
    modalLoadProdBtn: document.getElementById("modalLoadProdBtn"),
    modalLoadDevBtn: document.getElementById("modalLoadDevBtn"),
    modalLoadPluginDevBtn: document.getElementById("modalLoadPluginDevBtn"),
    modalLoadGuidesBtn: document.getElementById("modalLoadGuidesBtn"),
    modalLoadAboutBtn: document.getElementById("modalLoadAboutBtn"),
    modalTocControls: document.getElementById("modalTocControls"),
    docsModalScrollableContent: document.getElementById("docsModalScrollableContent"),
    confirmationModal: document.getElementById("confirmationModal"),
    confirmationModalTitle: document.getElementById("confirmationModalTitle"),
    confirmationModalMessage: document.getElementById("confirmationModalMessage"),
    confirmationModalConfirmBtn: document.getElementById("confirmationModalConfirmBtn"),
    confirmationModalCancelBtn: document.getElementById("confirmationModalCancelBtn"),
    confirmationModalConfirmBtnText: document.getElementById("confirmationModalConfirmBtnText"),
    confirmationModalCancelBtnText: document.getElementById("confirmationModalCancelBtnText"),
    rtspSaveButtonLabel: document.getElementById("rtspSaveButtonLabel"),
    processingSettingsLabel: document.getElementById("processingSettingsLabel"),
    pluginsListContainer: document.getElementById('pluginsListContainer'),
    pluginsListPlaceholder: document.getElementById('pluginsListPlaceholder'),
    pluginInstallUrl: document.getElementById('pluginInstallUrl'),
    pluginInstallBtn: document.getElementById('pluginInstallBtn'),
    pluginInstallUrlLabel: document.getElementById('pluginInstallUrlLabel'),
    pluginInstallBtnText: document.getElementById('pluginInstallBtnText'),
    pluginDevInfoText: document.getElementById('pluginDevInfoText'),
    openPluginDevDocsBtn: document.getElementById('openPluginDevDocsBtn'),
    clearHistoryButton: document.getElementById("clearHistoryButton"),

    videoElement: document.getElementById("webcam"),
    outputCanvas: document.getElementById("output_canvas"),
    gestureProgressCircle: document.querySelector(".gesture-progress") as SVGCircleElement | null,
    cooldownProgressCircle: document.querySelector(".cooldown-progress") as SVGCircleElement | null,
    currentGestureSpan: document.getElementById("currentGestureSpan"),
    currentConfidenceSpan: document.getElementById("currentConfidenceSpan"),
    confidenceBar: document.getElementById("confidenceBar"),
    holdTimeDisplay: document.getElementById("holdTimeDisplay"),
    holdTimeMetric: document.getElementById("holdTimeMetric"),
    topCenterStatus: document.getElementById("topCenterStatus"),
    progressTimersContainer: document.getElementById("progressTimersContainer"),
    connectingOverlay: document.getElementById("connectingOverlay"),
    connectingText: document.getElementById("connectingText"),
    videoToolbarContainer: document.getElementById("video-toolbar-container"),
    videoSizeToggleButton: document.getElementById("videoSizeToggleButton"),
    videoMirrorBtn: document.getElementById("videoMirrorBtn"),
    flipCameraBtn: document.getElementById("flipCameraBtn"),
    mobileVideoStopButton: document.getElementById("mobileVideoStopButton"),
    aiTuningBtn: document.getElementById("aiTuningBtn"),
    displayAdjustmentsBtn: document.getElementById("displayAdjustmentsBtn"),
    aiTuningPanel: document.getElementById("ai-tuning-panel"),
    displayAdjustmentsPanel: document.getElementById("display-adjustments-panel"),
    resetDisplayAdjustmentsBtn: document.getElementById("resetDisplayAdjustmentsBtn"),
    handTuningSliders: document.getElementById("handTuningSliders"),
    poseTuningSliders: document.getElementById("poseTuningSliders"),
    brightnessSlider: document.getElementById("brightnessSlider"),
    brightnessValue: document.getElementById("brightnessValue"),
    contrastSlider: document.getElementById("contrastSlider"),
    contrastValue: document.getElementById("contrastValue"),
    handDetectionConfidenceSlider: document.getElementById("handDetectionConfidenceSlider"),
    handDetectionConfidenceOutput: document.getElementById("handDetectionConfidenceOutput"),
    handPresenceConfidenceSlider: document.getElementById("handPresenceConfidenceSlider"),
    handPresenceConfidenceOutput: document.getElementById("handPresenceConfidenceOutput"),
    handTrackingConfidenceSlider: document.getElementById("handTrackingConfidenceSlider"),
    handTrackingConfidenceOutput: document.getElementById("handTrackingConfidenceOutput"),
    poseDetectionConfidenceSlider: document.getElementById("poseDetectionConfidenceSlider"),
    poseDetectionConfidenceOutput: document.getElementById("poseDetectionConfidenceOutput"),
    posePresenceConfidenceSlider: document.getElementById("posePresenceConfidenceSlider"),
    posePresenceConfidenceOutput: document.getElementById("posePresenceConfidenceOutput"),
    poseTrackingConfidenceSlider: document.getElementById("poseTrackingConfidenceSlider"),
    poseTrackingConfidenceOutput: document.getElementById("poseTrackingConfidenceOutput"),
  };

  const criticalElements = ["videoElement", "outputCanvas", "settingsTabs", "rtspAddNewButton", "wsStatusIndicator"];
  for (const key of criticalElements) { if (!elements[key]) throw new Error(`CRITICAL element missing: ${key}`); }

  return elements;
}